id: IAAC944C7
ocr_import_info:
  timestamp: '2023-08-16T06:25:56.816186+00:00'
  batch_id: batch-6137
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-16 06:35:19.076891+00:00
last_modified: 2023-08-16 06:35:19.076900+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN3438
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN3438
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྩ་ཤེས་ཀྱི་ཊཱི་ཀ་དང་ཚིག་གསལ་གྱི་དཀའ་གནད་དང་སྤྱི་སྡོམ།
  languages:
  - bo
  author: པ་ཚབ་ལོ་ཙཱ་བ་ཉི་མ་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9977480368835524
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN8574:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN8574
      total_pages: 410
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN8574.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9977480368835524
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
